# Generated by Django 5.1.3 on 2024-11-24 20:27

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
            ],
            options={
                "verbose_name": "season",
                "verbose_name_plural": "seasons",
                "ordering": ["start_date"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
