# Generated by Django 5.2.6 on 2025-09-14 19:23

from django.db import migrations

from teams.models import create_default_season


def create_first_season(apps, schema_editor):
    Season = apps.get_model("teams", "Season")
    start_date, end_date = create_default_season()
    Season.objects.get_or_create(start_date=start_date, end_date=end_date)


def remove_seasons(apps, schema_editor):
    Season = apps.get_model("teams", "Season")
    Season.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_first_season, remove_seasons),
    ]
