# Generated by Django 5.1.3 on 2024-11-24 20:28
from datetime import datetime

from django.db import migrations
from dateutil.relativedelta import relativedelta
from django.utils.timezone import now

def calculate_start_and_end_date() -> tuple[datetime, datetime]:
    start_date = now() + relativedelta(month=9, day=1)
    end_date = start_date + relativedelta(years=+1, days=-1)

    return start_date, end_date

def create_default_season(apps, schema_editor):
    Season = apps.get_model('teams', 'Season')
    start_date, end_date = calculate_start_and_end_date()

    try:
        Season.objects.create(start_date=start_date, end_date=end_date)
    except:
        pass

def remove_default_season(apps, schema_editor):
    Season = apps.get_model('teams', 'Season')
    start_date, end_date = calculate_start_and_end_date()

    try:
        Season.objects.get(start_date=start_date, end_date=end_date).delete()
    except:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_season, remove_default_season)]
