# Generated by Django 5.1.3 on 2024-11-24 20:52

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_create_default_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="name")),
                (
                    "abbreviation",
                    models.CharField(help_text="An abbreviated version of the role name", max_length=250, unique=True, verbose_name="abbreviation"),
                ),
                (
                    "staff_role",
                    models.BooleanField(
                        default=False, help_text="Staff roles are exported under the staff section for a given team", verbose_name="staff role"
                    ),
                ),
                (
                    "admin_role",
                    models.BooleanField(
                        default=False,
                        help_text="An admin role will grant rights to the user to manage and maintain a given team",
                        verbose_name="admin role",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="By adjusting the sort order, you can control which roles are displayed first, roles are ordered first based on order (low to high) before sorted by alphabet",
                        verbose_name="sort order",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
            ],
            options={
                "verbose_name": "team role",
                "verbose_name_plural": "team roles",
                "ordering": ["sort_order", "name"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
