# Generated by Django 5.1.3 on 2024-11-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_teamrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamrole",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=10,
                help_text="By adjusting the sort order, you can control which roles are displayed first, roles are ordered first based on order (low to high) before sorted by alphabet",
                verbose_name="sort order",
            ),
        ),
    ]
