# Generated by Django 5.1.3 on 2024-11-29 09:25

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_teamrole_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberPool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "enforce_unique_numbers",
                    models.BooleanField(
                        default=False,
                        help_text="Will not allow members that have a number to be assigned a number that is already in use by another member in the same pool",
                        verbose_name="enforce unique numbers",
                    ),
                ),
            ],
            options={
                "verbose_name": "number pool",
                "verbose_name_plural": "number pools",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
