# Generated by Django 5.2.6 on 2025-09-14 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_team_teammembership_team_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"], "verbose_name": "team", "verbose_name_plural": "teams"},
        ),
        migrations.AddField(
            model_name="teammembership",
            name="role",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="team_memberships", to="teams.teamrole", verbose_name="role"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammembership",
            name="season",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="team_memberships", to="teams.season", verbose_name="season"),
            preserve_default=False,
        ),
    ]
