# Generated by Django 5.1.3 on 2024-11-24 20:28

from django.db import migrations

def create_default_numberpool(apps, schema_editor):
    NumberPool = apps.get_model('teams', 'NumberPool')

    try:
        NumberPool.objects.create(name="default", enforce_unique_numbers=False)
    except:
        pass

def remove_default_numberpool(apps, schema_editor):
    NumberPool = apps.get_model('teams', 'NumberPool')

    try:
        NumberPool.objects.get(name="default").delete()
    except:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_numberpool"),
    ]

    operations = [migrations.RunPython(create_default_numberpool, remove_default_numberpool)]
