# Generated by Django 5.2.6 on 2025-09-14 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_team_options_teammembership_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.team", verbose_name="team"),
        ),
    ]
