# Generated by Django 5.2.6 on 2025-09-14 20:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models
from django.db import migrations, models

import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
        ("teams", "0006_alter_teammembership_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPicture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("picture", models.ImageField(upload_to=teams.models.team_season_file_path, verbose_name="picture")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "team picture",
                "verbose_name_plural": "team pictures",
                "ordering": ["team__name", "season__start_date"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="teammembership",
            options={"ordering": ["team__name", "role__sort_order", "number", "member__user__last_name", "member__user__first_name"], "verbose_name": "team membership", "verbose_name_plural": "team memberships"},
        ),
        migrations.AddField(
            model_name="teammembership",
            name="alternate_captain",
            field=models.BooleanField(default=False, verbose_name="alternate captain"),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="captain",
            field=models.BooleanField(default=False, verbose_name="captain"),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammembership",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name="number"),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(fields=("team", "season", "number"), name="unique_team_membership_number", violation_error_message="A team can only have one member for a given season and number."),
        ),
        migrations.AddField(
            model_name="teampicture",
            name="season",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.season", verbose_name="season"),
        ),
        migrations.AddField(
            model_name="teampicture",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.team", verbose_name="team"),
        ),
    ]
