# Generated by Django 5.1.3 on 2024-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_alter_numberpool_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numberpool",
            name="enforce_unique_numbers",
            field=models.BooleanField(
                default=False, help_text="Does not allow duplicate numbers to be assigned when checked", verbose_name="enforce unique numbers"
            ),
        ),
    ]
