# Generated by Django 5.1.3 on 2024-11-29 20:13

import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_member_password_change_required"),
        ("teams", "0008_alter_numberpool_enforce_unique_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, help_text="An optional short name", max_length=250, null=True, unique=True, verbose_name="short name"
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, max_length=250, populate_from="name", unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INT", "Internal"), ("EXT", "External")],
                        default="EXT",
                        help_text="Internal teams are not accessible through the API",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="teams/logo/", verbose_name="logo")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                (
                    "number_pool",
                    models.ForeignKey(
                        default="default",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="teams.numberpool",
                        to_field="name",
                        verbose_name="number pool",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="members.member", verbose_name="member")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.team", verbose_name="team")),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(through="teams.TeamMembership", to="members.member", verbose_name="members"),
        ),
    ]
