# Generated by Django 5.2.6 on 2025-09-27 15:38

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import markdownx.models
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0007_teampicture_alter_teammembership_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="title")),
                ("text", markdownx.models.MarkdownxField(verbose_name="text")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=["title"],
                        verbose_name="slug",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "In Review"), (2, "Released")],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Internal"),
                            (1, "External"),
                            (2, "Internal & External"),
                        ],
                        default=0,
                        help_text="Internal news is only visible to members after logging in. External news will be published on the website.",
                        verbose_name="type",
                    ),
                ),
                (
                    "publish_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time on which this item should be published. Only released items will be posted.",
                        verbose_name="Publish on",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(related_name="news_items", to="teams.team"),
                ),
            ],
            options={
                "verbose_name": "News item",
                "verbose_name_plural": "News items",
                "ordering": ["-created"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="news.newsitem",
                        verbose_name="News item",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
