# Generated by Django 5.2.6 on 2025-09-27 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="file",
            field=models.FileField(default="", upload_to="news/", verbose_name="file"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="main_picture",
            field=models.BooleanField(
                default=False,
                help_text="The main picture is the picture shown on the cover of the news item",
                verbose_name="main picture",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="picture",
            field=models.BooleanField(default=False, verbose_name="picture"),
        ),
        migrations.AddField(
            model_name="attachment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("main_picture", True)),
                fields=("news_item", "main_picture"),
                name="news_item_main_picture_unique",
                violation_error_message="Only one picture can be the main picture for a news item",
            ),
        ),
    ]
