# Generated by Django 5.2.6 on 2025-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_attachment_options_attachment_created_and_more"),
        ("teams", "0007_teampicture_alter_teammembership_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="news_items", to="teams.team"
            ),
        ),
    ]
