# Generated by Django 5.2.6 on 2025-09-15 06:22

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="name")),
                ("type", models.CharField(choices=[("event", "Event"), ("game", "Game"), ("practice", "Practice"), ("other", "Other")], default="other", max_length=10, verbose_name="type")),
                ("staff_registration_required", models.BooleanField(default=False, help_text="If set, requires staff members to also register their attendance for this activity type", verbose_name="staff registration required")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "activity type",
                "verbose_name_plural": "activity types",
                "ordering": ["name"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(verbose_name="name")),
                ("module", models.CharField(verbose_name="module")),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Opponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="opponents/logo/", verbose_name="logo")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "opponent",
                "verbose_name_plural": "opponents",
                "ordering": ["name"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
