# Generated by Django 5.2.6 on 2025-09-15 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="members.member", verbose_name="owner")),
                ("polymorphic_ctype", models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="polymorphic_%(app_label)s.%(class)s_set+", to="contenttypes.contenttype")),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
    ]
