# Generated by Django 5.2.6 on 2025-09-15 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activity"),
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
        ("teams", "0007_teampicture_alter_teammembership_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["start_time", "end_time"], "verbose_name": "activity", "verbose_name_plural": "activities"},
        ),
        migrations.AddField(
            model_name="activity",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="activity",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end time"),
        ),
        migrations.AddField(
            model_name="activity",
            name="gathering_time",
            field=models.DateTimeField(blank=True, help_text="Date and time when members need to be present at the location", null=True, verbose_name="gathering time"),
        ),
        migrations.AddField(
            model_name="activity",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="location"),
        ),
        migrations.AddField(
            model_name="activity",
            name="members",
            field=models.ManyToManyField(blank=True, help_text="Additional members to add, these are included in addition to the included teams", related_name="activities", to="members.member", verbose_name="members"),
        ),
        migrations.AddField(
            model_name="activity",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="registration deadline"),
        ),
        migrations.AddField(
            model_name="activity",
            name="require_registration",
            field=models.BooleanField(default=False, help_text="If set, members must register for the activity", verbose_name="require registration"),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="start time"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="teams",
            field=models.ManyToManyField(blank=True, related_name="activities", to="teams.team", verbose_name="teams"),
        ),
        migrations.AddField(
            model_name="activity",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="activity",
            name="type",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="activities.activitytype", verbose_name="type"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
