# Generated by Django 5.2.6 on 2025-09-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_alter_activity_options_activity_created_and_more"),
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("activity_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="activities.activity")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("activity_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="activities.activity")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                ("activity_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="activities.activity")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="PracticeOccurrence",
            fields=[
                ("activity_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="activities.activity")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "response",
                    models.CharField(
                        choices=[("no_response", "No response"), ("attending", "Attending"), ("not_attending", "Not attending"), ("selected", "Selected"), ("not_selected", "Not selected")],
                        default="no_response",
                        max_length=15,
                        verbose_name="response",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="activities.activity", verbose_name="activity")),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="members.member", verbose_name="member")),
            ],
            options={
                "verbose_name": "registration",
                "verbose_name_plural": "registrations",
                "unique_together": {("activity", "member")},
            },
        ),
    ]
