# Generated by Django 5.2.6 on 2025-09-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_event_game_practice_practiceoccurrence_registration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_time", "end_time", "title"], "verbose_name": "event", "verbose_name_plural": "events"},
        ),
    ]
