# Generated by Django 5.2.6 on 2025-09-15 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_alter_event_options"),
        ("teams", "0007_teampicture_alter_teammembership_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["start_time", "end_time", "title"], "verbose_name": "game", "verbose_name_plural": "games"},
        ),
        migrations.AddField(
            model_name="game",
            name="competition",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="games", to="activities.competition", verbose_name="competition"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="competition_game_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="competition id"),
        ),
        migrations.AddField(
            model_name="game",
            name="is_live",
            field=models.BooleanField(default=False, verbose_name="live"),
        ),
        migrations.AddField(
            model_name="game",
            name="opponent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="games", to="activities.opponent", verbose_name="opponent"),
        ),
        migrations.AddField(
            model_name="game",
            name="score_opponent",
            field=models.IntegerField(default=0, verbose_name="score opponent"),
        ),
        migrations.AddField(
            model_name="game",
            name="score_team",
            field=models.IntegerField(default=0, verbose_name="score team"),
        ),
        migrations.AddField(
            model_name="game",
            name="season",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="games", to="teams.season", verbose_name="season"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="team",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="games", to="teams.team", verbose_name="team"),
            preserve_default=False,
        ),
    ]
