# Generated by Django 5.2.6 on 2025-09-15 08:24

from django.db import migrations


def create_competition_group(apps, schema_editor):
    Competition = apps.get_model("activities", "Competition")

    try:
        Competition.objects.create(name="RBIHF", module="activities.competition.icehockey")
        Competition.objects.create(name="CEHL", module="activities.competition.icehockey")

    except:
        pass


def remove_competition_group(apps, schema_editor):
    Competition = apps.get_model("activities", "Competition")

    try:
        Competition.objects.get(name="RBIHF", module="activities.competition.icehockey").delete()
        Competition.objects.create(name="CEHL", module="activities.competition.icehockey")

    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_alter_game_options_game_competition_and_more"),
    ]

    operations = [migrations.RunPython(create_competition_group, remove_competition_group)]
