# Generated by Django 5.2.6 on 2025-09-15 10:34

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_create_competiton_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practice",
            options={"verbose_name": "practice", "verbose_name_plural": "practices"},
        ),
        migrations.AddField(
            model_name="practice",
            name="recurrences",
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
