# Generated by Django 5.2.6 on 2025-09-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_alter_practice_options_practice_recurrences"),
    ]

    operations = [
        migrations.AddField(
            model_name="practiceoccurrence",
            name="is_override",
            field=models.BooleanField(default=False, help_text="If set, this occurrence is an override and not part of the original series", verbose_name="is override"),
        ),
        migrations.AddField(
            model_name="practiceoccurrence",
            name="series",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="occurrences", to="activities.practice", verbose_name="series"),
            preserve_default=False,
        ),
    ]
