# Generated by Django 5.2.6 on 2025-09-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0009_practiceoccurrence_is_override_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practiceoccurrence",
            options={"verbose_name": "practice occurrence", "verbose_name_plural": "practice occurrences"},
        ),
    ]
