# Generated by Django 5.2.6 on 2025-09-15 10:55

from django.db import migrations


def create_default_activity_types(apps, schema_editor):
    ActivityType = apps.get_model("activities", "ActivityType")

    # Create default activity types
    try:
        ActivityType.objects.create(name="Event", type="event")
        ActivityType.objects.create(name="Game", type="game")
        ActivityType.objects.create(name="Practice", type="practice")
    except:
        pass


def remove_default_activity_types(apps, schema_editor):
    ActivityType = apps.get_model("activities", "ActivityType")

    # Remove default activity types
    try:
        ActivityType.objects.get(name="Event").delete()
        ActivityType.objects.get(name="Game").delete()
        ActivityType.objects.get(name="Practice").delete()
    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0010_alter_practiceoccurrence_options"),
    ]

    operations = [migrations.RunPython(create_default_activity_types, remove_default_activity_types)]
