# Generated by Django 5.2.6 on 2025-09-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0011_create_activity_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="competition",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="games", to="activities.competition", verbose_name="competition"),
        ),
    ]
