# Generated by Django 5.2.6 on 2025-09-21 19:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0012_alter_game_competition"),
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRegistration",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "response",
                    models.CharField(
                        choices=[("no_response", "No response"), ("attending", "Attending"), ("not_attending", "Not attending"), ("selected", "Selected"), ("not_selected", "Not selected")],
                        default="no_response",
                        max_length=15,
                        verbose_name="response",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("activity", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="activities.activity", verbose_name="activity")),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("member", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="members.member", verbose_name="member")),
            ],
            options={
                "verbose_name": "historical registration",
                "verbose_name_plural": "historical registrations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
