# Generated by Django 5.2.6 on 2025-09-21 20:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0013_historicalregistration"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalActivity",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="end time")),
                ("gathering_time", models.DateTimeField(blank=True, help_text="Date and time when members need to be present at the location", null=True, verbose_name="gathering time")),
                ("location", models.CharField(blank=True, max_length=255, null=True, verbose_name="location")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("require_registration", models.BooleanField(default=False, help_text="If set, members must register for the activity", verbose_name="require registration")),
                ("registration_deadline", models.DateTimeField(blank=True, null=True, verbose_name="registration deadline")),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="members.member", verbose_name="owner")),
                ("polymorphic_ctype", models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="contenttypes.contenttype")),
                ("type", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="activities.activitytype", verbose_name="type")),
            ],
            options={
                "verbose_name": "historical activity",
                "verbose_name_plural": "historical activities",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
