# Generated by Django 5.2.6 on 2025-09-21 21:04

import django.db.models.deletion
import django.utils.timezone
import recurrence.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0015_historicalgame_delete_historicalactivity"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalgame",
            name="is_live",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="score_opponent",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="score_team",
        ),
        migrations.AddField(
            model_name="historicalgame",
            name="created",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="HistoricalEvent",
            fields=[
                ("activity_ptr", models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name="+", to="activities.activity")),
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="end time")),
                ("gathering_time", models.DateTimeField(blank=True, help_text="Date and time when members need to be present at the location", null=True, verbose_name="gathering time")),
                ("location", models.CharField(blank=True, max_length=255, null=True, verbose_name="location")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("require_registration", models.BooleanField(default=False, help_text="If set, members must register for the activity", verbose_name="require registration")),
                ("registration_deadline", models.DateTimeField(blank=True, null=True, verbose_name="registration deadline")),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="members.member", verbose_name="owner")),
                ("polymorphic_ctype", models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="contenttypes.contenttype")),
                ("type", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="activities.activitytype", verbose_name="type")),
            ],
            options={
                "verbose_name": "historical event",
                "verbose_name_plural": "historical events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPractice",
            fields=[
                ("activity_ptr", models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name="+", to="activities.activity")),
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="end time")),
                ("gathering_time", models.DateTimeField(blank=True, help_text="Date and time when members need to be present at the location", null=True, verbose_name="gathering time")),
                ("location", models.CharField(blank=True, max_length=255, null=True, verbose_name="location")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("require_registration", models.BooleanField(default=False, help_text="If set, members must register for the activity", verbose_name="require registration")),
                ("registration_deadline", models.DateTimeField(blank=True, null=True, verbose_name="registration deadline")),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("recurrences", recurrence.fields.RecurrenceField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="members.member", verbose_name="owner")),
                ("polymorphic_ctype", models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="contenttypes.contenttype")),
                ("type", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="activities.activitytype", verbose_name="type")),
            ],
            options={
                "verbose_name": "historical practice",
                "verbose_name_plural": "historical practices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPracticeOccurrence",
            fields=[
                ("activity_ptr", models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name="+", to="activities.activity")),
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="end time")),
                ("gathering_time", models.DateTimeField(blank=True, help_text="Date and time when members need to be present at the location", null=True, verbose_name="gathering time")),
                ("location", models.CharField(blank=True, max_length=255, null=True, verbose_name="location")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("require_registration", models.BooleanField(default=False, help_text="If set, members must register for the activity", verbose_name="require registration")),
                ("registration_deadline", models.DateTimeField(blank=True, null=True, verbose_name="registration deadline")),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("is_override", models.BooleanField(default=False, help_text="If set, this occurrence is an override and not part of the original series", verbose_name="is override")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="members.member", verbose_name="owner")),
                ("polymorphic_ctype", models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="contenttypes.contenttype")),
                ("series", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="activities.practice", verbose_name="series")),
                ("type", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="activities.activitytype", verbose_name="type")),
            ],
            options={
                "verbose_name": "historical practice occurrence",
                "verbose_name_plural": "historical practice occurrences",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
