# Generated by Django 5.2.6 on 2025-09-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0016_remove_historicalgame_is_live_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="modified",
            new_name="updated",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="created",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="created",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="created",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="created",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="updated",
        ),
    ]
