# Generated by Django 5.2.6 on 2025-09-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0017_rename_modified_registration_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytype",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="logo"),
        ),
    ]
