# Generated by Django 5.2.6 on 2025-09-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0019_create_activity_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalgame",
            name="competition",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="description",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="registration_deadline",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="require_registration",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="season",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="title",
        ),
        migrations.RemoveField(
            model_name="historicalgame",
            name="type",
        ),
    ]
