# Generated by Django 5.2.6 on 2025-09-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0020_remove_historicalgame_competition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalevent",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="registration_deadline",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="require_registration",
        ),
        migrations.RemoveField(
            model_name="historicalevent",
            name="type",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="recurrences",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="registration_deadline",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="require_registration",
        ),
        migrations.RemoveField(
            model_name="historicalpractice",
            name="type",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="is_override",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="registration_deadline",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="require_registration",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="series",
        ),
        migrations.RemoveField(
            model_name="historicalpracticeoccurrence",
            name="type",
        ),
    ]
