"""
Django settings for the ClubManager project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config, Csv
from dj_database_url import parse as db_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1,192.168.1.100,192.168.1.170", cast=Csv())
INTERNAL_IPS = ["127.0.0.1"]

CSRF_TRUSTED_ORIGINS = config("DJANGO_CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# Application definition

INSTALLED_APPS = [
    # "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "constance",
    "rules.apps.AutodiscoverRulesConfig",
    "simple_history",
    "allauth",
    "allauth.account",
    "generic_notifications",
    "polymorphic",
    "recurrence",
    "tailwind",
    "markdownx",
    "webpush",
    "django_htmx",
    "theme.apps.ThemeConfig",
    "members.apps.MembersConfig",
    "notifications.apps.NotificationsConfig",
    "teams.apps.TeamsConfig",
    "activities.apps.ActivitiesConfig",
    "news.apps.NewsConfig",
    "sponsors.apps.SponsorsConfig",
    "messaging.apps.MessagingConfig",
    "frontend.apps.FrontendConfig"
]

if DEBUG:
    INSTALLED_APPS += ["debug_toolbar", "django_browser_reload"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

if DEBUG:
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware", "django_browser_reload.middleware.BrowserReloadMiddleware"]

# Debug Toolbar Configuration for ASGI compatibility
# DEBUG_TOOLBAR_CONFIG = {
#     "DISABLE_PANELS": {
#         "debug_toolbar.panels.redirects.RedirectsPanel",
#         "debug_toolbar.panels.templates.TemplatesPanel",
#     },
#     "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
# }

ROOT_URLCONF = "ClubManager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "notifications.context_processors.unread_notification_count",
                "sponsors.context_processors.get_main_sponsors",
                "messaging.context_processors.unread_messages_count",
                "ClubManager.context_processors.constance_configuration",
            ],
        },
    },
]

WSGI_APPLICATION = "ClubManager.wsgi.application"
ASGI_APPLICATION = "ClubManager.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": config("DJANGO_DATABASE_URL", default="sqlite:///db.sqlite3", cast=db_url)}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = config("DJANGO_TIME_ZONE", default="Europe/Brussels", cast=str)

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static_root"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_ROOT = BASE_DIR / "media_root"
MEDIA_URL = "media/"

TAILWIND_CLI_SRC_CSS = "static/css/source.css"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_CONFIG = {
    "CM_CLUB_NAME": (config("CM_CLUB_NAME", default="ClubManager", cast=str), "Club Name", str),
    "CM_CLUB_LOGO": ("", "Location of the club logo", str),
    "CM_CLUB_HOME_LOCATION": (config("CM_CLUB_HOME_LOCATION", default="Home", cast=str), "Location of the home games", str),
    "CM_DEFAULT_ACTIVITY_DURATION": (config("CM_DEFAULT_ACTIVITY_DURATION", default=3, cast=int), "Default duration of activities", int),
    "CM_DEFAULT_SEASON_MONTH": (config("CM_DEFAULT_SEASON_MONTH", default=8, cast=int), "Default season start month", int),
    "CM_DEFAULT_SEASON_DAY": (config("CM_DEFAULT_SEASON_DAY", default=1, cast=int), "Default season start day", int),
    "CM_DEFAULT_SEASON_DURATION": (config("CM_DEFAULT_SEASON_DURATION", default="1y", cast=str), "Default season duration", str),
    "CM_INSTAGRAM_HANDLE": (config("CM_INSTAGRAM_HANDLE", default="ClubManager", cast=str), "Instagram handle", str),
    "CM_CLUB_URL": (config("CM_CLUB_URL", default="http://127.0.0.1:8000", cast=str), "URL of ClubManager instance", str),
}

PHONENUMBER_DEFAULT_FORMAT = "INTERNATIONAL"
PHONENUMBER_DEFAULT_REGION = config("CM_CLUB_COUNTRY_CODE", default="BE", cast=str)

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = {"email*", "email2*", "password1*", "password2*"}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ]
}

TAILWIND_APP_NAME = "theme"

NPM_BIN_PATH = config("NPM_BIN_PATH", default="npm")

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": config("VAPID_PUBLIC_KEY", default=""),
    "VAPID_PRIVATE_KEY": config("VAPID_PRIVATE_KEY", default=""),
    "VAPID_ADMIN_EMAIL": config("VAPID_ADMIN_EMAIL", default=""),
}
