# Generated by Django 5.2.6 on 2025-09-27 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Logo will be visible as of this day",
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Logo will no longer be visible as of this date, leave empty to display indefinitly",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("logo", models.ImageField(upload_to="sponsors/logo/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "sponsor",
                "verbose_name_plural": "sponsors",
                "ordering": ["name"],
            },
        ),
    ]
