# Generated by Django 5.2.6 on 2025-09-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="main_sponsor",
            field=models.BooleanField(default=False),
        ),
    ]
