# Generated by Django 5.2.6 on 2025-09-08 08:55

import django.db.models.deletion
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="member", to=settings.AUTH_USER_MODEL, verbose_name="user")),
            ],
            options={
                "verbose_name": "member",
                "verbose_name_plural": "members",
                "ordering": ["user__last_name", "user__first_name"],
                "permissions": [("member_manager", "Can manage members")],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
