# Generated by Django 5.2.6 on 2025-09-08 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="birthday"),
        ),
        migrations.AddField(
            model_name="member",
            name="family_members",
            field=models.ManyToManyField(blank=True, related_name="family_members", to=settings.AUTH_USER_MODEL, verbose_name="family members"),
        ),
        migrations.AddField(
            model_name="member",
            name="license",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="license"),
        ),
    ]
