# Generated by Django 5.1.3 on 2024-11-10 10:04

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_family_members_member_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="birthday"),
        ),
        migrations.AddField(
            model_name="member",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, region=None, verbose_name="emergency phone number"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="license",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="license"),
        ),
        migrations.AddField(
            model_name="member",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default="", max_length=128, region=None, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="member",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="notes"),
        ),
    ]
