# Generated by Django 5.1.3 on 2024-11-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_birthday_member_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='If checked require the user to change their password at next logon', verbose_name='password change required'),
        ),
    ]
