# Generated by Django 5.2.6 on 2025-09-08 09:55

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_historicalmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="emergency_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="emergency phone number"),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="phone number"),
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="emergency phone number"),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name="phone number"),
        ),
    ]
