# Generated by Django 5.2.6 on 2025-09-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_historicalmember_emergency_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="family_members",
        ),
    ]
