# Generated by Django 5.2.6 on 2025-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_remove_member_family_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="family_members",
            field=models.ManyToManyField(blank=True, related_name="family", to="members.member", verbose_name="family members"),
        ),
    ]
