# Generated by Django 5.2.6 on 2025-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_member_family_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="family_members",
            field=models.ManyToManyField(blank=True, to="members.member", verbose_name="family members"),
        ),
    ]
