# Generated by Django 5.2.6 on 2025-09-14 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_alter_member_family_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="created",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="updated",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
