# Generated by Django 5.2.6 on 2025-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_historicalmember_created_historicalmember_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="token"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="token",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="token"
            ),
        ),
    ]
