# Generated by Django 5.2.6 on 2025-10-25 07:22
import secrets

from django.db import migrations


def generate_member_tokens(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    for member in Member.objects.all():
        member.token = secrets.token_urlsafe(32)
        member.save(update_fields=["token"])


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_historicalmember_token_member_token"),
    ]

    operations = [migrations.RunPython(generate_member_tokens, migrations.RunPython.noop)]
