# Generated by Django 5.2.6 on 2025-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_auto_20251025_0922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="token",
            field=models.CharField(
                blank=True, max_length=64, unique=True, verbose_name="token"
            ),
        ),
    ]
